name: 'Random Name Generator'
description: Creates randomized names
author: Peter Murray

inputs:
  max_length:
    description: The value for the variable to be stored
    required: false

  count:
    description: The number of names to generate
    default: 5
    required: false

outputs:
  names:
    description: The complete array of names that were generated as a JSON encoded string

  name:
    description: The first name that was generated

runs:
  using: node16
  main: 'dist/index.js'