const ADJECTIVES = [
    'animated',
    'automatic',
    'bookish',
    'bug-free',
    'cautious',
    'congenial',
    'crispy',
    'cuddly',
    'curly',
    'didactic',
    'effective',
    'expert',
    'fantastic',
    'fictional',
    'fluffy',
    'friendly',
    'furry',
    'fuzzy',
    'glowing',
    'ideal',
    'improved',
    'jubilant',
    'laughing',
    'legendary',
    'literate',
    'miniature',
    'musical',
    'potential',
    'probable',
    'psychic',
    'redesigned',
    'refactored',
    'reimagined',
    'scaling',
    'shiny',
    'silver',
    'solid',
    'special',
    'studious',
    'stunning',
    'sturdy',
    'super',
    'super-duper',
    'supreme',
    'symmetrical',
    'turbo',
    'ubiquitous',
    'upgraded',
    'urban',
    'verbose',
    'vigilant',
    'adorable',
    'beautiful',
    'clean',
    'drab',
    'elegant',
    'fancy',
    'glamorous',
    'handsome',
    'long',
    'magnificent',
    'plain',
    'quaint',
    'sparkling',
    'ugliest',
    'unsightly',
    'wide-eyed',
    'red',
    'orange',
    'yellow',
    'green',
    'blue',
    'purple',
    'gray',
    'black',
    'white',
    'alive',
    'better',
    'careful',
    'clever',
    'dead',
    'easy',
    'famous',
    'gifted',
    'hallowed',
    'helpful',
    'important',
    'inexpensive',
    'mushy',
    'odd',
    'powerful',
    'rich',
    'shy',
    'tender',
    'unimportant',
    'uninterested',
    'vast',
    'wrong',
    'clumsy',
    'fragile',
    'guilt',
    'itchy'
];


const NOUNS = [
    'people',
    'history',
    'way',
    'art',
    'world',
    'map',
    'health',
    'system',
    'computer',
    'meat',
    'year',
    'thanks',
    'music',
    'person',
    'reading',
    'method',
    'data',
    'food',
    'theory',
    'law',
    'bird',
    'problem',
    'software',
    'control',
    'knowledge',
    'power',
    'ability',
    'economics',
    'love',
    'adventure',
    'barnacle',
    'bassoon',
    'broccoli',
    'carnival',
    'chainsaw',
    'couscous',
    'disco',
    'dollop',
    'doodle',
    'engine',
    'enigma',
    'eureka',
    'fiesta',
    'fortnight',
    'funicular',
    'garbanzo',
    'giggle',
    'goggles',
    'guacamole',
    'guide',
    'happiness',
    'invention',
    'journey',
    'lamp',
    'meme',
    'memory',
    'palm-tree',
    'pancake',
    'parakeet',
    'potato',
    'robot',
    'phone',
    'sniffle',
    'spoon',
    'spork',
    'succotash',
    'telegram',
    'train',
    'tribble',
    'umbrella',
    'waddle',
    'waffle',
    'winner'
];

export function generateName(maxLength: number = 48): string {
    const prefix = Math.random() < 0.25 ? 'octo-' : '';

    let name: string;
    let counter = 0;
    do {
        name = `${adjective()}-${prefix}${noun()}`;

        if (counter++ > 100) {
            throw new Error('Unable to generate a name within the length limit.');
        }
    } while (name.length > maxLength);

    return name;
}

function noun() {
    return NOUNS[Math.floor(Math.random() * NOUNS.length)]
}

function adjective() {
    return ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
}